### ISSUE TITLE
Issue with hybrid species

### ISSUE THREAD

**Issue by philippbayer** [nleguillarme/taxonerd#11]
Thank you so much for this amazing package, it saves me a ton of work.

I have one minor issue and I wonder whether there's a workaround - in fisheries we have complex hybrids denoted with a bunch of brackets and Xs. Taxonerd pulls these apart and reports separate species, but it would be nicer if the hybrids would be reported together.

Example:

    $ cat testtext.txt
    (Megalobrama amblycephala x Megalobrama terminalis) x (Megalobrama amblycephala x Parabramis pekinensis)

That's a real taxonomic entity :) https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1798809

Running taxonerd on that:

    $  taxonerd ask -m en_core_eco_biobert -f testtext.txt

OR

    $ taxonerd ask -m en_core_eco_md -f testtext.txt

will both return:

```
T0      LIVB 1 25       Megalobrama amblycephala
T1      LIVB 28 50      Megalobrama terminalis
T2      LIVB 55 79      Megalobrama amblycephala
T3      LIVB 82 103     Parabramis pekinensis
```

But in this case, it would be more accurate to retain the hybrid structure and report the entire string, as the hybrid is a separate species from the other four. Would that be possible?

**Comment by nleguillarme** [comment]
This one is tricky !

My first idea was to extend TaxoNERD's pipeline with [rule-based matching](https://spacy.io/usage/rule-based-matching). The problem is that spaCy does not support nested patterns. So I ended up with adding two matchers, one for hybrids, the second for hybrids of hybrids

```python
import spacy

nlp = spacy.load("en_core_eco_biobert")
ruler_1 = nlp.add_pipe("entity_ruler", name = "hybrid_ruler", config={"overwrite_ents":True})

patterns = [{
    "label":"HYBRID", 
    "pattern":[
        {"TEXT":"(", "OP":"*"},
        {"ENT_TYPE":"LIVB", "OP":"+"}, 
        {"LOWER":"x"}, 
        {"ENT_TYPE":"LIVB", "OP":"+"}, 
        {"TEXT":")", "OP":"*"},
    ],
    }]
ruler_1.add_patterns(patterns)

ruler_2 = nlp.add_pipe("entity_ruler", name = "hybrid_of_hybrid_ruler", config={"overwrite_ents":True})
patterns = [{
    "label":"HYBRID", 
    "pattern":[
        {"TEXT":"(", "OP":"*"},
        {"ENT_TYPE":"HYBRID", "OP":"+"}, 
        {"LOWER":"x"}, 
        {"ENT_TYPE":"HYBRID", "OP":"+"}, 
        {"TEXT":")", "OP":"*"},
    ],
    }]
ruler_2.add_patterns(patterns)

text="(Megalobrama amblycephala x Megalobrama terminalis) x (Megalobrama amblycephala x Parabramis pekinensis)"
doc = nlp(text)

print(doc.ents)
((Megalobrama amblycephala x Megalobrama terminalis) x (Megalobrama amblycephala x Parabramis pekinensis),)
``` 

It works, but I don't think it's very robust.
Maybe a better solution would be to write [a custom component](https://spacy.io/usage/rule-based-matching#models-rules-ner).

**Comment by philippbayer** [comment]
Thank you so much for your fast reply. 

I see what you mean! I'm sure there'll be hybrids of hybrids of hybrids :) However, for now that's 'good enough' for me, in my data I haven't seen those hybrids^3.  I will add your hybrids-of-hybrids rules, that should at least solve my problem!
