### ISSUE TITLE
v1.5.2 "Not found" when attempting install

### ISSUE THREAD

**Issue by maxfarrell** [nleguillarme/taxonerd#13]
Hello, 

`install.packages("https://github.com/nleguillarme/taxonerd/releases/download/v1.5.2/taxonerd_for_R_1.5.2.tar.gz", repos=NULL)`

Results in HTTP status  "404 Not Found"

**Comment by nleguillarme** [comment]
Oh, I did not complete the release process ! I do it right now

**Comment by maxfarrell** [comment]
Yes this works! Thanks!
