### ISSUE TITLE
ERROR: Failed building wheel for nmslib

### ISSUE THREAD

**Issue by serendipity-zhang** [nleguillarme/taxonerd#22]
When I use "pip install taxonerd" command to install taxonerd, it shows this error. It happens both on Linux and Windows systems.

**Comment by nleguillarme** [comment]
What version of Python are you using?

**Comment by serendipity-zhang** [comment]
I installed the conda env with Python 3.8.  It is running OK now.

**Comment by nleguillarme** [comment]
Great !
