### ISSUE TITLE
404 error when installing taxonerd 1.5.4 in R

### ISSUE THREAD

**Issue by maxfarrell** [nleguillarme/taxonerd#25]
Just wanted to flag that using the following code from the README leads to an `HTTP status was '404 Not Found'` error when installing:

`install.packages("https://github.com/nleguillarme/taxonerd/releases/download/v1.5.4/taxonerd_for_R_1.5.4.tar.gz", repos=NULL)`

**Comment by nleguillarme** [comment]
I simply forgot to publish the R package. That should be fixed now :)

**Comment by nleguillarme** [comment]
I am closing the issue, please feel free to reopen it if the error is still there !
