### ISSUE TITLE
Error in py_call_impl(callable, dots$args, dots$keywords) ||| R/taxonerd

### ISSUE THREAD

**Issue by Otoliths** [nleguillarme/taxonerd#5]
Dear all,
I am trying to run an R script for Initialize the taxonomic NER engine to run on a Windows 10.

Here is the error:
```
library(taxonerd)
# Initialize the taxonomic NER engine
ner <- init.taxonerd("en_ner_eco_md", abbrev=TRUE, sent=FALSE, link="ncbi_lite", thresh=0.85, gpu=F)
```
```
Your CPU supports instructions that this binary was not compiled to use: AVX AVX2
For maximum performance, you can install NMSLIB from sources 
pip install --no-binary :all: nmslib
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  BadZipFile: File is not a zip file 
```

**Comment by nleguillarme** [comment]
Hi @Otoliths, thank you for using TaxoNERD

Before using init.taxonerd you must:
1. install the python package using install.taxonerd
2. install a NER model using install.model. Available models are en_ner_eco_md and  en_ner_eco_biobert
3. then you can initialize the NER engine using init.taxonerd

You can refer to the vignette, the whole process is explained in it.

**Comment by Otoliths** [comment]
Hi @nleguillarme, 

Thank you very much for your timely reply. I have solved it based on your tips. 

Thanks.
