### ISSUE TITLE
In addition to linking reference taxonomy, TaxoNERD can link more user-defined contents？

### ISSUE THREAD

**Issue by Otoliths** [nleguillarme/taxonerd#6]
Hi @nleguillarme ,

I asked again.

1. Whether TaxoNERD can be linked more user-defined contents to extract information users like from literature in future versions？For example, if I want to extract species distribution information, if I build a georeference dataset(Name of location) in *.tsv ,how can I use TaxoNERD tool to extract the information I want based on reference ones?I guess you need to add a parameter to link user-defined referenced dataset. Or you have a better way.

2. As this may take a long time to link online, can the current version (v1.3.0) supported 4 linkers(gbif_backbone,taxref,ncbi_taxonomy and ncbi_taxonomy_lite) run them locally? it's easier to link them locally on workstation with enough RAM.

Looking forward to your reply.

Thanks

**Comment by nleguillarme** [comment]
Hi @Otoliths 

1. At the moment, TaxoNERD is designed specifically for taxonomic entity recognition. It is our plan to include additional entities in the future, maybe in the same or in another tool. But this requires that annotated datasets are available. By chance, the COPIOUS corpus which is used to train our models also contains annotations for species distribution information (see http://www.nactem.ac.uk/copious/). If I have time in the next few months, I may try to train a model for species distribution information extraction. Or if you want, you can try to train your own model based on TaxoNERD's training configuration files.
2. Entity linking is done offline. Simply, TaxoNERD has to download all the required files the first time you run the linking engine. This may take some time, but it is only done once, and subsequent calls to the linking engine are way faster.

**Comment by Otoliths** [comment]
Hi @nleguillarme,

Thank you very much for your reply and I am looking forward to the release of the  new TaxoNERD version.

**Comment by nleguillarme** [comment]
Hi @Otoliths 

Since the last release (1.4.0), TaxoNERD can be easily combined with rule-based NER to detect additional entity types.
See [this notebook](https://github.com/nleguillarme/taxonerd/blob/a58808e5808d74e341d0d98bc64dfebd7a670b81/extensions/entity_ruler.ipynb) for more details on how to proceed.

**Comment by Otoliths** [comment]
Hi @nleguillarme ,
      Thank you！I can't wait to try this fantastic package.
