### ISSUE TITLE
Issue with tokens included in more than one span

### ISSUE THREAD

**Issue by maxfarrell** [nleguillarme/taxonerd#7]
Hi! Thanks for a great tool :) - I'm trying to tag taxonomic entities in a series of abstracts. I've saved each as a separate .txt file and using these as part of your vignette workflow. 

Using the `find.in.corpus` function, I get the following error which stops annotation:

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: [E1010] Unable to set entity information for token 151 which is included in more than one span in entities, blocked, missing or outside.

Detailed traceback:
  File "/root/.virtualenvs/r-taxonerd/lib/python3.8/site-packages/taxonerd/taxonerd.py", line 87, in find_in_corpus
    df = self.find_in_file(filename, output_dir)
  File "/root/.virtualenvs/r-taxonerd/lib/python3.8/site-packages/taxonerd/taxonerd.py", line 100, in find_in_file
    df = self.find_in_text(text)
  File "/root/.virtualenvs/r-taxonerd/lib/python3.8/site-packages/taxonerd/taxonerd.py", line 112, in find_in_text
    doc = self.ner(text)
  File "/root/.virtualenvs/r-taxonerd/lib/python3.8/site-packages/taxonerd/taxonerd.py", line 155, in ner
    doc.set_ents(ents)
  File "spacy/tokens/doc.pyx", line 770, in spacy.tokens.doc.Doc.set_ents
```
I tried to figure out which abstract is causing the issue by writing the annotations to a separate folder. However, it looks like the function does not annotate the source files in the same order as they are in the folder (alphabetical), so I'm not sure how to find the source file causing this error.  I will repeat this using find.in.text and looping over the texts directly and report back which token is causing the issue.

I know spaCy has some way of dealing with overlapping spans, but for now I wonder if it's possible to fix this when accessing taxonerd via R + reticulate?

**Comment by nleguillarme** [comment]
Hi @maxfarrell ! Thank you for using TaxoNERD, I'd be happy to hear about your use case, and have your feedback about your experience as a user.

Regarding your problem, you can also call find.in.file for each abstract in your corpus. Once you've figured out which abstracts is causing this issue, please send it to me, as well as the configuration of your NER engine : do you use sentence segmentation ? abbreviation detection (from the stack trace, I guess you do) ? entity linking ?

Once I'll be able to identify what is causing this error, I am pretty sure it won't be too much work to fix it.

**Comment by maxfarrell** [comment]
Hi Nicolas, 

I have emailed you ten examples of texts that fail with this error. The same error comes up when using find.in.text or when using find.in.file. My NER engine is "en_ner_eco_md", abbrev=TRUE, sent=FALSE, link="ncbi_taxonomy", thresh=0.85, gpu=FALSE

**Comment by nleguillarme** [comment]
Hi @maxfarrell
I could not reproduce the error with the first three abstracts you sent me.
Could you try updating your version of TaxoNERD ? `install.taxonerd(version="1.3.2")`

**Comment by nleguillarme** [comment]
Hi @maxfarrell, I may have reproduce your error. I will keep you posted.

**Comment by maxfarrell** [comment]
Hi @nleguillarme I was using this version of taxonerd, but I can try re-installing. I also noticed that while I installed taxonerd 1.3.2 as per the main github Readme, I installed the 1.3.0 version of the eco_md model `install.model(model="en_ner_eco_md", version="1.3.0")` as per the R vignette. Could this difference in package versus model version be the issue?

**Comment by nleguillarme** [comment]
Hi @maxfarrell I found out what is going wrong !
The error is caused by scispacy's AbbreviationDetector sometimes returning overlapping spans.
In addition, there are cases where abbreviations overlap with normal entities.
I fixed the bug, I will release a new version of taxonerd very soon.

**Comment by maxfarrell** [comment]
Excellent @nleguillarme - I'm glad I could help find the issues. Let me know when the new version is up! I'm looking forward to giving it a spin

**Comment by maxfarrell** [comment]
Hello @nleguillarme I just wanted to followup and say the issue might not be completely resolved. 

I am using taxonerd 1.3.3 and the following model initialization:

`ner <- init.taxonerd("en_ner_eco_md", abbrev=TRUE, sent=FALSE, link="ncbi_taxonomy", thresh=0.85, gpu=FALSE)
`
The example abstract below causes the same span error saying that token 206 is included in more than one span. 

However, when I initialize the model with `abbrev=FALSE, sent=FALSE`, there is no span error thrown and entities are detected. 

Span errors are thrown with `abbrev=TRUE, sent=TRUE`, and for some reason a different error is given with `abbrev=FALSE, sent=TRUE` (something about `Extension 'sent_id' already exists on Span` and it fails to initialize the model)

Example of an abstract that causing the error:

"Rabies Virus Infection in Eptesicus fuscus Bats Born in Captivity (Naive Bats) -- The study of rabies virus infection in bats can be challenging due to quarantine requirements, husbandry concerns, genetic differences among animals, and lack of medical history. To date, all rabies virus (RABV) studies in bats have been performed in wild caught animals. Determining the RABV exposure history of a wild caught bat based on the presence or absence of viral neutralizing antibodies (VNA) may be misleading. Previous studies have demonstrated that the presence of VNA following natural or experimental inoculation is often ephemeral. With this knowledge, it is difficult to determine if a seronegative, wild caught bat has been previously exposed to RABV. The influence of prior rabies exposure in healthy, wild caught bats is unknown. To investigate the pathogenesis of RABV infection in bats born in captivity (naive bats), naive bats were inoculated intramuscularly with one of two Eptesicus fuscus rabies virus variants, EfV1 or EfV2. To determine the host response to a heterologous RABV, a separate group of naive bats were inoculated with a Lasionycteris noctivagans RABV (LnV1). Six months following the first inoculation, all bats were challenged with EfV2. Our results indicate that naive bats may have some level of innate resistance to intramuscular RABV inoculation. Additionally, naive bats inoculated with the LnV demonstrated the lowest clinical infection rate of all groups. However, primary inoculation with EfV1 or LnV did not appear to be protective against a challenge with the more pathogenic EfV2."
